name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ops-image:latest
      - name: Build Success
        run: echo "Docker image built successfully!"
      - name: Verify image
        run: docker images | grep ops-image