name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ops-image:latest
      - name: Run container
        run: |
          docker run -d --name ops-image -p 5000:5000 ops-image:latest
          curl --fail http://localhost:5000