name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-flask-app:latest .

      - name: Verify deployment
        run: |
          docker run -d --name my-flask-app -p 5000:5000 my-flask-app:latest
          curl --fail http://localhost:5000