name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/my-flask-app:${GITHUB_SHA}

      - name: Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest

      - name: Verify deployment
        run: |
          docker run -d --name my-flask-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
          curl --fail http://localhost:500
